player_data_save_time: 300
commands_before_items: false
claim_kit_short_command: false
close_inventory_on_claim: false
nbt_alternative_data_save: false
hide_kits_with_permissions: false
drop_items_if_full_inventory: false
close_inventory_no_permission: true
preview_inventory_requires_permission: false

preview-inventory:
  enabled: true
  size: 54
  back-item: true
  back-item-slot: 45

mysql_database:
  enabled: false
  host: localhost
  port: 3306
  username: root
  password: root
  database: database

inventory:
  size: 45
  pages_names:
    1: "&9Kits"
    2: "&bVIP Kits"
  items: {}