
claim_kit_short_command: false
nbt_alternative_data_save: false
preview_inventory_requires_permission: false

inventory:
  size: 45

preview-inventory:
  enabled: true
  size: 54
  back-item: true
  back-item-slot: 45

Config:
    hide_kits_with_permissions: false
    close_inventory_on_claim: false
    drop_items_if_full_inventory: false
    commands_before_items: false
    player_data_save_time: 300
    inventory_pages_names:
      1: "&9Kits"
      2: "&bVIP Kits"
    mysql_database:
      enabled: false
      host: localhost
      port: 3306
      username: root
      password: root
      database: database