Config:
    inventorySize: 45
    previewInventorySize: 54
    preview_inventory_back_item_slot: 45
    kit_preview: true
    kit_preview_back_item: true
    hide_kits_with_permissions: false
    close_inventory_on_claim: false
    drop_items_if_full_inventory: false
    commands_before_items: false
    preview_inventory_requires_permission: false
    claim_kit_short_command: false
    kit_error_sound: BLOCK_NOTE_BLOCK_PLING;10;0.1
    kit_claim_sound: ENTITY_PLAYER_LEVELUP;10;1.5
    kit_page_sound: BLOCK_LAVA_POP;10;1
    player_data_save_time: 300
    nbt_alternative_data_save: false
    inventory_pages_names:
      1: "&9Kits"
      2: "&bVIP Kits"
    mysql_database:
      enabled: false
      host: localhost
      port: 3306
      username: root
      password: root
      database: database