
claim_kit_short_command: false
nbt_alternative_data_save: false
preview_inventory_requires_permission: false

Config:
    inventorySize: 45
    previewInventorySize: 54
    preview_inventory_back_item_slot: 45
    kit_preview: true
    kit_preview_back_item: true
    hide_kits_with_permissions: false
    close_inventory_on_claim: false
    drop_items_if_full_inventory: false
    commands_before_items: false
    player_data_save_time: 300
    inventory_pages_names:
      1: "&9Kits"
      2: "&bVIP Kits"
    mysql_database:
      enabled: false
      host: localhost
      port: 3306
      username: root
      password: root
      database: database