main: pk.ajneb97.PlayerKits
version: 2.25.1
name: PlayerKits
api-version: 1.13
softdepend: [Vault,PlaceholderAPI]
authors: [Ajneb97, Sliide_]

commands:
  kit:
    description: Main command of PlayerKits
    aliases: kits